### ISSUE TITLE
Gesture sensor is now running, but doesn't log any gestures

### ISSUE THREAD

**Issue by jrtderonde** [sparkfun/SparkFun_APDS-9960_Sensor_Arduino_Library#9]
Hey,

I recently bought a APDS 9960 sensor. I installed it to my Arduino (correctly, 3.3V) and tried the GestureTest.ino example, but I can't keep it to log the correctly. I've also tried the Proximity & ColorSensor examples which are working and logging correctly.

When I upload and run the GestureTest.ino, it returns the following information to the serial monitor.

SparkFun APDS-9960 - GestureTest
APDS-9960 initialization complete
Gesture sensor is now running

Does anybody know what's up?

**Comment by ShawnHymel** [comment]
Which Arduino are you using? There have been reports of the gesture example not working correctly on some Arduino boards.

When you swipe your hand across the sensor, nothing appears in the Serial monitor?

**Comment by jrtderonde** [comment]
I'm using an Arduino UNO board. And no, nothing seems to appear in the serial monitor. For the other examples there is information shown in the serial monitor though.

**Comment by ShawnHymel** [comment]
It sounds like you have everything hooked up correctly--do you have the INT pin connected to an interrupt pin on the Arduino (e.g. pin 2)? 

The UNO is a known good board with the APDS-9960, so I recommend reaching out to SparkFun's Tech Support staff to get a better diagnosis than what I can give:
 [https://www.sparkfun.com/technical_assistance](https://www.sparkfun.com/technical_assistance)

**Comment by jrtderonde** [comment]
Yes, I wired up everything correctly. Triple checked the wires, and the other examples are working correctly. 

SCL => A5
SCA => A5
INT => 2

**Comment by jrtderonde** [comment]
By the way, I bought [this](https://www.tinytronics.nl/shop/nl/sensoren/robotdyn-apds-9960-gesture-detectie-module?sort=rating&order=DESC&limit=100) sensor instead of the one from SparkFun. It was the only one that was being sold by my regular Arduino parts distributor. I bought two and I tested them from two different Arduinos, same problem.

**Comment by ShawnHymel** [comment]
Ah...then I don't know how much SparkFun's technical support would be able to help. There are, what appears to be, some transistors added to that board. So, I'm not super sure what's going on. You'll probably want to turn on debugging (change `#define DEBUG` to 1 in src/SparkFun_APDS9960.h). See if that offers any insight into what's happening with the gesture engine.

**Comment by jrtderonde** [comment]
Thanks dude! I'll try it tomorrow, see what I find 👍

**Comment by jrtderonde** [comment]
Have a look at this paste. Can't really tell anything from the information.

https://pastebin.com/mJNk7LK6

**Comment by jrtderonde** [comment]
I changed `if( !setLEDBoost(LED_BOOST_300) ) {` to `if( !setLEDBoost(LED_BOOST_100) ) {` and it seems to work now. It only returns a lot of `NONE` values for swipes. Any idea how this could be fixed?

**Comment by jrtderonde** [comment]
Got it to work. Had to work around some variables which actually made it work. 

I used `LED_BOOST_100` and `GGAIN_2X` and the module is working like a charm.

**Comment by ShawnHymel** [comment]
Glad to hear it worked out!

**Comment by shrajna15** [comment]
could u pls tell me...where did u make these changes because m facing a similar issue with my APDS-9960

**Comment by brasofilo** [comment]
I'm having the same issue with a Robotdyn APDS, @jrtderonde solution worked to fix the UNO but I can't get a Micro to work.

> could u pls tell me...where did u make these changes because m facing a similar issue with my APDS-9960

@shrajna15, changes need to be made inside your Sketch/libraries folder, look for the APDS library and change the `GGAIN_2X` in the `.h` file and `LED_BOOST_100` in the `.cpp` file.

**Comment by ashutosh-akss** [comment]
I am having same issue and , I tried changing changes suggested by @jrtderonde  but no luck, 

Except gesture, everthing else is working fine like RGB & proximity, can i assume that module is working and I only have issue with code ? I am using ESP32 Dev module v1 for this

**Comment by Rob58329** [comment]
I was having the same issue with an "Adafruit APDS9960" board with an ESP8266 (D1-mini).  My APDS996 all worked fine at 5V using an Arduino-Uno; but with the ESP8266 (ie. with Vss=3.3V), although the RGB and also Proximity-detector worked fine, the Gesture-Sensor did not work.

I suspect this is because the voltage/current available after the Adafruit on-board AP2112 regulator is not quite enough for the IR-LED diode to work the Gesture-Sensor.  (I suspect extra capacitors somewhere after the regulator might help as I note that the Sparkfun-APDS9960 board which is designed for 3.3v only uses much bigger capacitors than the Adafruit one - but I havent tried this yet.)

HOWEVER (using "https://github.com/sparkfun/SparkFun_APDS-9960_Sensor_Arduino_Library"), changing  "setLEDBoost(LED_BOOST_300)"" to "setLEDBoost(LED_BOOST_100)" as per  @jrtderonde above worked for me.  (IE. now the Gesture-Sensor works at 3.3v with my ESP8266.)  (The default SparkFun library sets LED_BOOST_300, which in theory causes the IR-LED current to be 100mA*300% which is 300mA, so I'm guessing this is just too much for the 3.3V supply I have on the ESP8266.)

In theory, if using the "https://github.com/adafruit/Adafruit_APDS9960" library, I beleive that the command "apds.setLED(APDS9960_LEDDRIVE_100MA,APDS9960_LEDBOOST_100PCNT);" should do the same thing, but for some reason although this does enable the Gesture-Sensor to work sometimes, for me it does not work as reliably as the above "SparkFun" library does, so perhaps the "SparkFun" library changes another setting too.)

**Comment by Thorndogz** [comment]
Hi There, one issue I was facing was that the development board I was using did not have a pull up resistor on the interrupt line, make sure you check this as it may resolve your issue :-).

**Comment by abhyamgupta123** [comment]
the same problem is what I faced to run this module in Arduino NANO, and the solution given by @Rob58329  worked like a charm for this,  As he told just download the repo  "https://github.com/sparkfun/SparkFun_APDS-9960_Sensor_Arduino_Library"), unzip it and paste into your default location of library for arduino,(for me it was /home/abhyam/Arduino/libraries) now change the file named "SparkFun_APDS9960.cpp" in src folder of this library asa told by @Rob58329  and suggested by @jrtderonde, "setLEDBoost(LED_BOOST_300)" to "setLEDBoost(LED_BOOST_100)"  now save and close the folder, 
Now restart the arduino IDE , and upload the sample code , now this will probably work in your case too. The example file for gesture control is in File->Examples->SparkFun APDS-9960 rgb and gesture sensor->GestureTest. 

Thanks to all.

**Comment by ronthema** [comment]
Love the internets.  Thanks @Rob58329 and @jrtderonde@!

**Comment by RozatkarAjay** [comment]
> I am having same issue and , I tried changing changes suggested by @jrtderonde but no luck,
> 
> Except gesture, everthing else is working fine like RGB & proximity, can i assume that module is working and I only have issue with code ? I am using ESP32 Dev module v1 for this
Can you please share your code Im working with APDs9960 with ESP32 and its not working its just worked as a proximity switch

**Comment by Jokanaan6** [comment]
hello i would like to ask what to change in the GGAIN_2x as i am also having the same problem with the output always being NONE
